[options]
addons_path = O:\odoo\odoo19-dev\odoo\addons,O:\odoo\odoo19-dev\odoo\odoo\addons
admin_passwd = $pbkdf2-sha512$600000$pxQC4Hxv7T3n3LvXOicEYA$GVTkDh7rCy0tbnEByRUJRpMtS7.OMLb5AyD/b3asDpFypzt9emyytkIYLNTtxU6nL1VhBmOxM62lo86.6ZOK7w
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo
data_dir = O:\odoo\odoo19-dev\data
db_name = False
dbfilter = .*
http_interface = 0.0.0.0
http_port = 8069
log_handler = :INFO
log_level = info
list_db = True
proxy_mode = False
without_demo = False

